name: Railway CI
permissions:
  contents: read

on:
  push:
    branches:
      - 'trunk'
    paths:
      - 'railway.json'
      - '.github/workflows/railway-validate.yml'
  pull_request:
    branches:
      - 'trunk'
    paths:
      - 'railway.json'
      - '.github/workflows/railway-validate.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - uses: sourcemeta/jsonschema@6393abde8a2927f74a90f18f433b6ef427553adc
    - name: Validate railway.json against schema
      run: jsonschema metaschema railway.json --verbose --http
