name: Validate railway.json
permissions:
  contents: read

on:
  push:
    paths:
      - 'railway.json'
  pull_request:
    paths:
      - 'railway.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: sourcemeta/jsonschema@1988b2bbc5c53b5c2b3791ea445a3ab41dd92b55
    - name: Validate railway.json against schema
      run: jsonschema metaschema railway.json
